### PR TITLE
Fix: Add static error state

### PR DESCRIPTION
**Pull request by krisrjohnson21**
IntegSoft requested a static error state. I used dotcom styling to add a duplicate Password field showing an error state. 

Note that this static error field is only for IntegSoft reference as to how an error state should look. 

Asana ticket (see comments for context): https://app.asana.com/0/0/1200981513142981/f

### CODE REVIEW

**Comment by krisrjohnson21** [comment]
There is no reference in the [SSO Annotation slides](https://mbta.sharepoint.com/:p:/s/CTD/EVcdHrlzby9KhYGCqGsmEj0BocFlI-JB-CsOJOJkcNGnhw?email=krisjohnson%40MBTA.com&e=4%3Aif8p3Z&wdLOR=cD59EB8E3-0DA7-774D-BFA1-F7C22879B7EE) for this.
Screen Shot 2021-11-23 at 2 06 05 PM

**Review by ryan-mahoney — CHANGES_REQUESTED** [review]
Screenshot from 2021-11-24 12-00-07

The coding looks good!

Some minor changes:
- the heading/errors messages should be on separate lines
- there could be multiple errors on the form, an unordered list might make sense

**Comment by krisrjohnson21** [comment]
Love these changes! Implemented now, along with text changes to mirror the screenshot above
Screen Shot 2021-11-24 at 12 25 33 PM
.

**Review by ryan-mahoney — APPROVED** [review]
Nice!

One small item: Can you remove the "X" image (which would close or hide the notification)? Some notifications are ephemeral, in which case, closing/hiding the notice makes sense, but in this use case, the only way to make it go away is to resubmit the form.

**Comment by krisrjohnson21** [comment]
Makes sense! SVG and associated style removed 👍

**Pull request merged**
